# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [9]:
import numpy as np


In [8]:
### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [10]:
A = np.arange(1, 16).reshape(3,5)

In [13]:
import numpy as np

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [14]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


In [15]:
D = B - C
print("Elementwise subtraction B - C:")
print(D)
E = B@C

print("Elements of.Multiplication")
print(E)

Elementwise subtraction B - C:
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
Elements of.Multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [4]:
import numpy as np

B = np.arange(1, 10).reshape(3, 3)

# 1. Exponentiate each element (elementwise)
exp_B = np.exp(B)

# 2. Minimum value in the whole matrix
min_a= np.min(B)

# 3. Minimum value in each row
min_row_vals = np.min(B, axis=1)

# 4. Minimum value in each column
min_col_vals = np.min(B, axis=0)

# 5. Index of minimum value in the flattened matrix
min_index = np.argmin(B)

# 6. Index of minimum value in each row
min_row_indices = np.argmin(B, axis=1)

# 7. Sum of all elements
total_sum = np.sum(B)

# 8. Mean of each column
col_mean = np.mean(B, axis=0)

# 9. Median of each column
col_median = np.median(B, axis=0)

# Print results
print("Exponentiated B:\n", exp_B)
print("\nMinimum value in B:", min_a)
print("Minimum value in each row:", min_row_vals)
print("Minimum value in each column:", min_col_vals)
print("Index of minimum value in flattened B:", min_index)
print("Index of min in each row:", min_row_indices)
print("Sum of all elements:", total_sum)
print("Mean of each column:", col_mean)
print("Median of each column:", col_median)

Exponentiated B:
 [[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in B: 1
Minimum value in each row: [1 4 7]
Minimum value in each column: [1 2 3]
Index of minimum value in flattened B: 0
Index of min in each row: [0 0 0]
Sum of all elements: 45
Mean of each column: [4. 5. 6.]
Median of each column: [4. 5. 6.]


In [9]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [10]:
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
B[1]

array([4, 5, 6])

**Answer:**

In [12]:
B[0]

array([1, 2, 3])

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [13]:
B


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
for i in B:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


In [18]:
for  i in B.flat:
     print(i)

1
2
3
4
5
6
7
8
9


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [16]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


This means that axis=0 represents 2 elements,in which axis=1 reperesents 5 elements in each sub array and axis 2 represents 3 arrays in each group.

# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [ ]:
m1 = np.array ([[1, 2], [3, 4]])
m2 = np.array ([1, 1])
print (m1 + m2)

### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [ ]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

In [ ]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [2]:

import numpy as np
m1 = np.array ([[1, 2], [3, 4]])
m2 = np.array ([1, 1])
print (m1 + m2)

[[2 3]
 [4 5]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [3]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [6]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[  0   1   2 123]


In [5]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
